p_406 = {'edf': '/Users/rotemfalach/projects/epileptic_activity/results/406/P406_overnightData.edf',
         'all_ch_names': ['SEEG RA1-REF', 'SEEG RA2-REF', 'SEEG RA3-REF', 'SEEG RA4-REF', 'SEEG RA5-REF',
                          'SEEG RA6-REF', 'SEEG RA7-REF', 'SEEG RAH1-REF', 'SEEG RAH2-REF', 'SEEG RAH3-REF',
                          'SEEG RAH4-REF', 'SEEG RAH5-REF', 'SEEG RAH6-REF', 'SEEG RAH7-REF', 'SEEG RPHG1-REF',
                          'SEEG RPHG2-REF', 'SEEG RPHG3-REF', 'SEEG RPHG4-REF', 'SEEG RPHG5-REF', 'SEEG RPHG6-REF',
                          'SEEG RPHG7-REF', 'SEEG RACr1-REF', 'SEEG RACr2-REF', 'SEEG RACr3-REF', 'SEEG RACr4-REF',
                          'SEEG RACr5-REF', 'SEEG RACr6-REF', 'SEEG RACr7-REF', 'SEEG RSMA1-REF', 'SEEG RSMA2-REF',
                          'SEEG RSMA3-REF', 'SEEG RSMA4-REF', 'SEEG RSMA5-REF', 'SEEG RSMA6-REF', 'SEEG RSMA7-REF',
                          'SEEG RMPF1-REF', 'SEEG RMPF2-REF', 'SEEG RMPF3-REF', 'SEEG RMPF4-REF', 'SEEG RMPF5-REF',
                          'SEEG RMPF6-REF', 'SEEG RMPF7-REF', 'SEEG LA1-REF', 'SEEG LA2-REF', 'SEEG LA3-REF',
                          'SEEG LA4-REF', 'SEEG LA5-REF', 'SEEG LA6-REF', 'SEEG LA7-REF', 'SEEG LAH1-REF',
                          'SEEG LAH2-REF', 'SEEG LAH3-REF', 'SEEG LAH4-REF', 'SEEG LAH5-REF', 'SEEG LAH6-REF',
                          'SEEG LAH7-REF', 'SEEG LPHG1-REF', 'SEEG LPHG2-REF', 'SEEG LPHG3-REF', 'SEEG LPHG4-REF',
                          'SEEG LPHG5-REF', 'SEEG LPHG6-REF', 'SEEG LPHG7-REF', 'SEEG LACr1-REF', 'SEEG LACr2-REF',
                          'SEEG LACr3-REF', 'SEEG LACr4-REF', 'SEEG LACr5-REF', 'SEEG LACr6-REF', 'SEEG LACr7-REF',
                          'SEEG LSMA1-REF', 'SEEG LSMA2-REF', 'SEEG LSMA3-REF', 'SEEG LSMA4-REF', 'SEEG LSMA5-REF',
                          'SEEG LSMA6-REF', 'SEEG LSMA7-REF', 'EEG C3-REF', 'EEG C4-REF', 'EEG PZ-REF', 'EOG EOG1-REF',
                          'EOG EOG2-REF', 'EMG EMG1-REF', 'EMG EMG2-REF', 'EEG A1-REF', 'EEG A2-REF', 'EKG EKG1-REF',
                          'EKG EKG2-REF', 'X1 X1-REF'],
         'scalp': ['EOG EOG1-REF', 'EOG EOG2-REF', 'EEG C3-REF', 'EEG C4-REF', 'EEG PZ-REF'],
         'spikes_RAH1': '/Users/rotemfalach/projects/epileptic_activity/results/406/406_RAH_spikes.csv',
         'spikes_LAH1': '/Users/rotemfalach/projects/epileptic_activity/results/406/406_LAH_spikes.csv',
         'spikes_RA1': '/Users/rotemfalach/projects/epileptic_activity/results/406/406_RA1_spikes.csv',
         'spikes_RMPF2': '/Users/rotemfalach/projects/epileptic_activity/results/406/406_RMPF2_spikes.csv',
         'spikes_RPHG1': '/Users/rotemfalach/projects/epileptic_activity/results/406/406_RPHG1_spikes.csv'}

p_D036 = {'edf': '/Users/rotemfalach/projects/epileptic_activity/results/D036/D036_15_01_21a.edf',
          'all_ch_names': ['RA 01', 'RA 02', 'RA 03', 'RA 04', 'RA 05', 'RA 06', 'RA 07', 'RA 08', 'RMH 01', 'RMH 02',
                           'RMH 03', 'RMH 04', 'RMH 05', 'RMH 06', 'RMH 07', 'RMH 08', 'LTT 01', 'LTT 02', 'LTT 03',
                           'LTT 04', 'LTT 05', 'LTT 06', 'LTT 07', 'LTT 08', 'LA 01', 'LA 02', 'LA 03', 'LA 04',
                           'LA 05', 'LA 06', 'LA 07', 'LA 08', 'LSTGp 01', 'LSTGp 02', 'LSTGp 03', 'LSTGp 04',
                           'LSTGp 05', 'LSTGp 06', 'LSTGp 07', 'LSTGp 08', 'LH 01', 'LH 02', 'LH 03', 'LH 04', 'LH 05',
                           'LH 06', 'LH 07', 'LH 08', 'LITG 01', 'LITG 02', 'LITG 03', 'LITG 04', 'LITG 05', 'LITG 06',
                           'LITG 07', 'LITG 08', 'LPHGp 01', 'LPHGp 02', 'LPHGp 03', 'LPHGp 04', 'LPHGp 05', 'LPHGp 06',
                           'LPHGp 07', 'LPHGp 08', 'LSTGa 01', 'LSTGa 02', 'LSTGa 03', 'LSTGa 04', 'LSTGa 05',
                           'LSTGa 06', 'LSTGa 07', 'LSTGa 08', 'F4', 'C4', 'P4', 'O2', 'F8', 'T8', 'P8', 'F3', 'C3',
                           'P3', 'O1', 'F7', 'T7', 'P7', 'Fz', 'Cz', 'Pz', 'EKG', 'Pulse'],
          'scalp': ['Fz', 'Cz', 'Pz'],
          'channels': ['EOG1-REF', 'EOG2-REF', 'C3-REF', 'C4-REF', 'PZ-REF', 'SEEG RAH1-REF'],
          'spikes_RA_08': '/Users/rotemfalach/projects/epileptic_activity/results/D036/D036_RA08_spikes.csv',
          'spikes_RMH_08': '/Users/rotemfalach/projects/epileptic_activity/results/D036/D036_RMH8_spikes.csv',
          'spikes_LTT_08': '/Users/rotemfalach/projects/epileptic_activity/results/D036/D036_LTT08_spikes.csv',
          'spikes_LPHGp_04': '/Users/rotemfalach/projects/epileptic_activity/results/D036/D036_LPHGp4_spikes.csv'}

p_D037 = {'edf': '/Users/rotemfalach/projects/epileptic_activity/results/D037/D037_28_01_21a.edf',
          'all_ch_names': ['ROF 01', 'ROF 02', 'ROF 03', 'ROF 04', 'ROF 05', 'ROF 06', 'ROF 07', 'ROF 08', 'RAC 01',
                           'RAC 02', 'RAC 03', 'RAC 04', 'RAC 05', 'RAC 06', 'RAC 07', 'RAC 08', 'RA 01', 'RA 02',
                           'RA 03', 'RA 04', 'RA 05', 'RA 06', 'RA 07', 'RA 08', 'RH 01', 'RH 02', 'RH 03', 'RH 04',
                           'RH 05', 'RH 06', 'RH 07', 'RH 08', 'RposT 01', 'RposT 02', 'RposT 03', 'RposT 04',
                           'RposT 05', 'RposT 06', 'RposT 07', 'RposT 08', 'RTO 01', 'RTO 02', 'RTO 03', 'RTO 04',
                           'RTO 05', 'RTO 06', 'RTO 07', 'RTO 08', 'LAH 01', 'LAH 02', 'LAH 03', 'LAH 04', 'LAH 05',
                           'LAH 06', 'LAH 07', 'LAH 08', 'LposT 01', 'LposT 02', 'LposT 03', 'LposT 04', 'LposT 05',
                           'LposT 06', 'LposT 07', 'LposT 08', 'F4', 'C4', 'P4', 'O2', 'F3', 'C3', 'P3', 'O1', 'F7',
                           'T7', 'P7', 'Fz', 'Cz', 'T4', 'Pz', 'EKG', 'Pulse'],
          'scalp': ['Fz', 'Cz', 'Pz'],
          'spikes_LAH_01': '/Users/rotemfalach/projects/epileptic_activity/results/D037/D037_LAH1_spikes.csv',
          'spikes_RAC_05': '/Users/rotemfalach/projects/epileptic_activity/results/D037/D037_RAC5_spikes.csv',
          'spikes_RH_01': '/Users/rotemfalach/projects/epileptic_activity/results/D037/D037_RH1_spikes.csv'}